services:
  ocserv:
    build: .
    restart: unless-stopped
    container_name: ocserv
    hostname: www.example.com
    ports:
      #- 443:443/udp
      - 5443:443
   volumes:
     - ./ocserv-data:/etc/ocserv
    sysctls:
    - net.ipv4.ip_forward=1
    cap_add:
    - NET_ADMIN
    security_opt:
    - no-new-privileges
